- clusters/G4TTree.C
> works with root6

- IonGun/DisplayOn.C
- block/DisplayOn.C
- block/Fun4All_G4_block.C
The new DisplayAction needs to call PHG4Reco::ApplyDisplayAction() to set the G4VisAttributes
> Block display fix

- Momentum/DisplayOn.C
- Momentum/Fun4All_G4_Momentum.C
- Momentum/vis.mac
This PR adds a macro with simple cylinders - 6 layers for silicon, 1 for an EMCal, 1 for an HCal
> start with momentum tutorial

- AnaTutorial/README.md
- AnaTutorial/macro/Fun4All_AnaTutorial.C
- AnaTutorial/src/AnaTutorial.cc
- AnaTutorial/src/AnaTutorial.h
- AnaTutorial/src/AnaTutorialLinkDef.h
- AnaTutorial/src/Makefile.am
- AnaTutorial/src/autogen.sh
- AnaTutorial/src/configure.ac
This PR introduces an analysis package that can be used as a reference for finding generally useful information like reconstructed tracks, clusters, and truth information. It is intended to be used as a reference for new people to sPHENIX as a way to document analysis objects that are used in a variety of ways.
> Analysis Package Tutorial

- AnaTutorial/macro/Fun4All_AnaTutorial_Jets.C
- AnaTutorial/macro/phpythia8.cfg
Added tutorial macro for running jet sims. Tested on 20 events, collects high pT jets with analysis tutorial package.
> Added tutorial macro for running jet sims

- AnaTutorial/README.md
Update readme with default sphenix source script
> Update readme with source script

- Momentum/DisplayOn.C
- Momentum/Fun4All_G4_Momentum.C
- Momentum/init_gui_vis.mac
- Momentum/vis.mac
This PR makes some minor tweaks - remove the calorimeters and replaces them with a black hole. Fix the momentum to 4GeV/c so we can plot easily from the root file
> Fix momentum

- CreateSubsysRecoModule/README.md
- CreateSubsysRecoModule/macros/Fun4All_MySimpleReco.C
- CreateSubsysRecoModule/source/create_me.sh
- README.md
This PR shows how to create a SubsysReco module using the new CreateSubsysRecoModule.pl script which lives under offline/framework/fun4all (together with the base class SubsysReco.h)
> Create subsys reco module

- CreateSubsysRecoModule/README.md
- CreateSubsysRecoModule/macros/Fun4All_MySimpleReco.C
- CreateSubsysRecoModule/source/create_me.sh
> Modify script

- Momentum/DisplayOn.C
- Momentum/Fun4All_G4_Momentum.C
- Momentum/Fun4All_G4_Momentum_Projection.C
- Momentum/Fun4All_G4_Momentum_Projection_Calorimeters.C
- Momentum/Fun4All_G4_Momentum_Projection_Detectors.C
- Momentum/README.md
- Momentum/vis.mac
- README.md
This PR is a revamp of the momentum tutorial. Added macros to show how projections are done and cleaned out the root5 remnants
> Modernize momentum tutorial

- materialscan/Fun4All_G4_sPHENIX.C
- materialscan/G4Setup_sPHENIX.C
- materialscan/README.md
- materialscan/matscan.C
- materialscan/plot_matscan.C
This PR removes root5 from the material scan example. Lots of clarifications in the README.md
> Remove root5

- AnaTutorial/macro/Fun4All_AnaTutorial.C
- AnaTutorial/src/AnaTutorial.cc
- AnaTutorial/src/AnaTutorial.h
Fix memory leaks with unique pointers rather than raw pointers.
> fix memory leaks

- myjetanalysis/macro/Fun4All_JetAna.C
- myjetanalysis/src/Makefile.am
- myjetanalysis/src/MyJetAnalysis.cc
- myjetanalysis/src/MyJetAnalysis.h
- myjetanalysis/src/MyJetAnalysisLinkDef.h
- myjetanalysis/src/configure.ac
This PR makes this usable for the eic. The EIC tracking creates a TrackMap node instead of an SvtxTrackMap to avoid explanations what that means. It is the same object internally, so just checking for TrackMap if SvtxTrackMap is not found solves that
> Add trackmap node

- MagneticField/macros/ReadFieldMap.C
- MagneticField/src/FieldMapReadBack.cc
- MagneticField/src/FieldMapReadBack.h
- MagneticField/src/Makefile.am
- MagneticField/src/autogen.sh
- MagneticField/src/configure.ac
This is a little code snippet which gets the pointer to the fieldmap from the node tree (or creates a new one if it doesn't exist)
> add example to read back field from DST

- MagneticField/src/FieldMapReadBack.cc
oops - small correction, all numbers need units otherwise it it G4 internal units (whatever they are)
> add unit to location coordinates

- AnaTutorial/macro/Fun4All_AnaTutorial.C
- AnaTutorial/macro/Fun4All_AnaTutorial_Jets.C
- AnaTutorial/src/AnaTutorial.cc
This PR updates the macros in the tutorial to be compatible with the latest versions.
> update tutorial macros

- AnaTutorial/README.md
- AnaTutorial/macro/G4Setup_EICDetector.C
Updates AnaTutorial macro and adds some discussion in the readme about what to do if the macros are out of sync.
> Tutorial updates

- MagneticField/macros/Print3dFieldMap.C
- MagneticField/src/FieldMapReadBack.cc
- MagneticField/src/FieldMapReadBack.h
Add methods to load fieldmap from cmd line and print fieldvalues
> Print 3dfield

- MagneticField/macros/Print3dFieldMap.C
- Momentum/Fun4All_G4_Momentum_Projection_Detectors.C
This PR fixes a mismatch for the cylinder radius and its associated projection
> Fix momentum macro

- cylinder/Fun4All_G4_Cylinder.C
- cylinder/MyHitTTree.C
thie PR removes root 5 from the cylinder tutorial
> ditch root5

- MagneticField/macros/Print3dFieldMap.C
- MagneticField/macros/ReadFieldMap.C
Minor macro changes for the magnetic field reading
> update macros to return fieldmap reader

- myjetanalysis/src/MyJetAnalysis.cc
- myjetanalysis/src/MyJetAnalysis.h
move initializers into class def, remove using namespace std
> cosmetic changes for myjetanalysis

- myjetanalysis/src/Makefile.am
- myjetanalysis/src/MyJetAnalysis.cc
Make this tutorial module compile with new clang version
> Compile with clang

- AnaTutorial/src/AnaTutorial.cc
- AnaTutorial/src/Makefile.am
- AnaTutorial/src/configure.ac
The PR removes the root5 compatibility and adds a bit of cleanup for the Anatutorial to conform our coding standards (clang-tidy, clang-format)
> Remove linkdef ana

- AnaTutorial/src/AnaTutorial.cc
Accompanies https://github.com/sPHENIX-Collaboration/coresoftware/pull/1990
> Update to new global vertex package

- AnaTutorial/macro/condor_scripts/run_tutorial.job
- AnaTutorial/macro/condor_scripts/run_tutorial.sh
Fixes for the AnaTutorial, we should promote bash, it's easier
> use bash, source /opt/sphenix/core scripts

- AnaTutorial/src/AnaTutorial.cc
Updates to new global vertex to build
> refactor: Update to new globalvertex type

- CaloDataAnaRun24pp/macro/Fun4All_CaloTreeGen.C
Yeah the l in GL1Packet is apparently supposed to be capitalized :(
> Fix to steering macro in CaloAna Tutorial

- CaloDataAnaRun24pp/src/caloTreeGen.cc
> Updated trigger vector to scaled vector

- CaloDataAnaRun24pp/README
- CaloDataAnaRun24pp/macro/Fun4All_CaloTreeGen.C
- CaloDataAnaRun24pp/macro/getGoodRunList.py
This update includes:
- Addition of tower masking protocol to the Fun4All macro
- The addition of Blair's good run script to generate file lists
- Instructions in the readme on how to use the output of the good run finder in the CreateDstList pearl script in order to actually get run lists for analysis.
> Updating Calorimeter Tutorial Code 

- CaloDataAnaRun24pp/macro/Fun4All_CaloTreeGen.C
Added some flags to improve CDB functionality which is necessary for the calibration tools
> Updating Tutorial for Better CDB Utilization

- CaloDataAnaRun24pp/macro/Fun4All_CaloHistGen.C
This update adds two DST inputs for DST_CALO and DST_CALOFITTING to be used, and includes example files in the constructor.
> Update for dual DST input

- AnaTutorial/src/Makefile.am
- CaloAna/src/Makefile.am
- MagneticField/src/Makefile.am
- MyOwnTTree/src/Makefile.am
- myjetanalysis/src/Makefile.am
- sPHENIX_sims/Calib/Makefile.am
This should get our tutorials to compile again
> use -isystem for offline_main includes

- HEPData/README.md
github text formatting hide variable in the installation, fixing it
> fixed commands to install
